# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0002_auto_20160217_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='fl_name'),
        ),
    ]
