# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0003_auto_20160220_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first_name'),
        ),
    ]
