# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0006_auto_20160220_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='first_name',
            new_name='fl_name',
        ),
    ]
