# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_testquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
