# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_delete_testquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collaborators',
            field=models.ManyToManyField(related_name='tasks', to='splash.myUser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to='splash.myUser'),
        ),
    ]
