# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160217_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
