# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_iscomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
