# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20160218_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collaborators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
