# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20160219_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
